spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        show-sql: true
        use_sql_comments: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  kafka:
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_AUTH_USERNAME}' password='${KAFKA_AUTH_PASSWORD}';

    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    topics:
      pw_reset_notification: pw_reset_notification
      account_activation_notification: account_activation_notification

security:
  jwt:
    prefix: "Bearer "
    auth_token_expiration: 604800000
    pw_reset_token_expiration: 3600000
    account_activation_token_expiration: 172800000
    secret: ${JWT_SECRET}
    issuer: http://localhost